##################################
#         Global settings        #
##################################
listen_addresses = ['127.0.0.1:5350', '[::1]:5350']
server_names = ['adguard-dns-family','cisco']
####
#
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = false
require_nolog = true
require_nofilter = false
disabled_server_names = []
force_tcp = true
timeout = 2500
keepalive = 30
cert_refresh_delay = 240
fallback_resolver = '9.9.9.9:53'
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = false
# block_unqualified = true

##############
# user_name = 'nobody'
# proxy = "socks5://127.0.0.1:1080"
# http_proxy = "http://127.0.0.1:8888"
# refused_code_in_responses = false
lb_strategy = 'p2'
lb_estimator = true
log_level = 0
log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
use_syslog = false
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
tls_cipher_suite = [52392, 49199]
# offline_mode = false

##################################################################################
#        Route queries for specific domains to a dedicated set of servers        #
##################################################################################
forwarding_rules = 'dnscrypt-forwarding-rules.txt'

###############################
#        Cloaking rules       #
###############################
cloaking_rules = 'dnscrypt-cloaking-rules.txt'

###########################
#        DNS cache        #
###########################
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

###############################
#        Query logging        #
###############################
[query_log]
  file = '/var/log/dnscrypt-proxy/dnscrypt-query.log'
  format = 'tsv'
  # ignored_qtypes = ['DNSKEY', 'NS']

############################################
#        Suspicious queries logging        #
############################################
[nx_log]
  file = '/var/log/dnscrypt-proxy/dnscrypt-nxdomain.log'
  format = 'tsv'

######################################################
#        Pattern-based blocking (blacklists)         #
######################################################
[blacklist]
  # blacklist_file = 'dnscrypt-blacklist-domains.txt'
  blacklist_file = 'yj-blacklist-domains.txt'
  log_file = '/var/log/dnscrypt-proxy/dnscrypt-blacklist-domains.log'
  log_format = 'tsv'

###########################################################
#        Pattern-based IP blocking (IP blacklists)        #
###########################################################
[ip_blacklist]
  blacklist_file = 'dnscrypt-blacklist-ips.txt'
  log_file = '/var/log/dnscrypt-proxy/dnscrypt-blacklist-ips.log'
  log_format = 'tsv'

######################################################
#   Pattern-based whitelisting (blacklists bypass)   #
######################################################
[whitelist]
  whitelist_file = 'dnscrypt-whitelist.txt'
  log_file = '/var/log/dnscrypt-proxy/dnscrypt-whitelisted.log'
  log_format = 'tsv'

[sources]

  # [sources.'public-resolvers']
  # urls = ['file://public-resolvers.md'] 
# 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
   # cache_file = 'public-resolvers.md'
   #  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
   # refresh_delay = 72
   # prefix = ''

#########################
#        Servers        #
#########################
[static]
  [static.'adguard-dns-family']
  stamp= 'sdns://AQMAAAAAAAAAFDE3Ni4xMDMuMTMwLjEzMjo1NDQzILgxXdexS27jIKRw3C7Wsao5jMnlhvhdRUXWuMm1AFq6ITIuZG5zY3J5cHQuZmFtaWx5Lm5zMS5hZGd1YXJkLmNvbQ'
  [static.'cisco']
  stamp = 'sdns://AQAAAAAAAAAADjIwOC42Ny4yMjAuMjIwILc1EUAgbyJdPivYItf9aR6hwzzI1maNDL4Ev6vKQ_t5GzIuZG5zY3J5cHQtY2VydC5vcGVuZG5zLmNvbQ'
  [static.'google']
  stamp = 'sdns://AgUAAAAAAAAAAKAe9iTP_15r07rd8_3b_epWVGfjdymdx-5mdRZvMAzBuSB2gCRHoBmTGj8AQwTFP9xsGyw3jcS-j3Ozn9nJad-0RQ5kbnMuZ29vZ2xlLmNvbQ0vZXhwZXJpbWVudGFs'
